# main.yml
when:
  branch: [main, dev]

steps:
  generate:
    when:
      event: [tag, push, manual]
    image: codeberg.org/gameplayer-8/markdown-html

    commands:
      - sh worker.sh

  publish:
    when:
      event: [tag, push, manual]
    image: codeberg.org/gameplayer-8/gitio

    commands:
      - export SYSTEM_BRANCH="$(basename "$CI_COMMIT_REF")-pages"
      - if [ "$(basename "$CI_COMMIT_REF")" = "main" ]; then export SYSTEM_BRANCH="pages"; fi
      - gitio branch GIT_BRANCH:"$SYSTEM_BRANCH"

    environment:
      USERNAME:
        from_secret: SYSTEM_TOKEN_PASSWD
